services:
  - type: web
    name: whatsapp-automation
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd whatsapp_project && gunicorn whatsapp_project.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-automation-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID  
        sync: false
        - key: GEMINI_API_KEY
        sync: fal

databases:
  - name: whatsapp-automation-db
    plan: free
