services:
  - type: web
    name: whatsapp-automation
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd whatsapp_project && gunicorn whatsapp_project.wsgi:application"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: whatsapp-automation-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID  
        sync: false

databases:
  - name: whatsapp-automation-db
    plan: free
