# Generated by Django 5.2.4 on 2025-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='Whatsapp', max_length=20)),
                ('raw_text', models.TextField()),
                ('is_relevant', models.BooleanField(default=False)),
                ('forwarded_to_telegram', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'whatsapp_messages_messagelog',
            },
        ),
    ]
