# Generated by Django 5.2.4 on 2025-07-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='messagelog',
            table='whatsapp_messages_messagelog',
        ),
    ]
